spring:
  datasource:
    url: jdbc:mysql://localhost:3307/quiz_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: eOAcZwBHCgYcwoTj1n9U55HoAkBH9jaB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
