name: Full Stack CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'Backend/SpringbootBackend/**'
      - 'Frontend/VueFrontend/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Backend/SpringbootBackend/**'
      - 'Frontend/VueFrontend/**'

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn -B compile --file Backend/SpringbootBackend/pom.xml
      #- name: Build with Maven
      #  run: mvn -B package --file Backend/SpringbootBackend/pom.xml
      #- name: Run Tests
      #  run: mvn test --file Backend/SpringbootBackend/pom.xml
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: pass

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --prefix Frontend/VueFrontend
      #- name: Lint
      #  run: npm run lint --prefix Frontend/VueFrontend
      - name: Build
        run: npm run build --prefix Frontend/VueFrontend
      #- name: Run Vitest
      #  run: npm run test:unit --prefix Frontend/VueFrontend
      #- name: Cypress tests
      #  uses: cypress-io/github-action@v2
      #  with:
      #    start: npm run serve --prefix Frontend/VueFrontend
      #    wait-on: 'http://localhost:8080'
      #    config: baseUrl=http://localhost:8080

  deploy:
    needs: [ build-and-test-backend, build-and-test-frontend ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backend Docker image
        run: |
          docker build -t sanderskofsrud/fullstackproject-backend:latest ./Backend/SpringbootBackend
          docker push sanderskofsrud/fullstackproject-backend:latest

      - name: Build and push Frontend Docker image
        run: |
          docker build -t sanderskofsrud/fullstackproject-frontend:latest ./Frontend/VueFrontend
          docker push sanderskofsrud/fullstackproject-frontend:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/username/fullstackproject
            docker-compose down
            docker-compose pull
            docker-compose up -d
      
